[package]
name = "wgpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glfw = "0.44.0"
env_logger = "0.9"
log = "0.4"
wgpu = "0.12"
pollster = "0.2.5"